config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'plans#home'
  resources 'plans'
  resources 'macrocycles'
  resources 'mesocycles'
  resources 'microcycles'
  resources 'days'
  resources 'exercises'

end

app/models/day.rb
class Day < ActiveRecord::Base
	belongs_to :microcycle
	has_many :exercises
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :day
end

app/models/macrocycle.rb
class Macrocycle < ActiveRecord::Base
	belongs_to :plan
	has_many :mesocycles
end

app/models/mesocycle.rb
class Mesocycle < ActiveRecord::Base
	belongs_to :macrocycle
	has_many :microcycles
end

app/models/microcycle.rb
class Microcycle < ActiveRecord::Base
	belongs_to :mesocycle
	has_many :days
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :user
	has_many :macrocycles
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :plans
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
	def new
		@day = Day.new
	end

	def create
		@day = Day.new(day_params)
		if @day.save
			redirect_to plans_path
		else
			render :new
		end
	end

	def edit
		@day = Day.find(params[:id])
	end

	def update
		@day = Day.find(params[:id])

		if @day.update_attributes(day_params)
			redirect_to plans_path
		else
			render :edit
		end
	end

	def destroy
		@day = Day.find(params[:id])
		@day.destroy
		redirect_to plans_path
	end

	private
	def day_params
		params.require(:day).permit(:title, :microcycle_id)
	end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def new
		@exercise = Exercise.new
	end

	def create
		@exercise = Exercise.new(exercise_params)
		if @exercise.save
			redirect_to plans_path
		else
			render :new
		end
	end

	def edit
		@exercise = Exercise.find(params[:id])
	end

	def update
		@exercise = Exercise.find(params[:id])

		if @exercise.update_attributes(exercise_params)
			redirect_to plans_path
		else
			render :edit
		end
	end

	def destroy
		@exercise = Exercise.find(params[:id])
		@exercise.destroy
		redirect_to plans_path
	end

	private
	def exercise_params
		params.require(:exercise).permit(:name, :day_id)
	end
end

app/controllers/macrocycles_controller.rb
class MacrocyclesController < ApplicationController

	def new
		@macrocycle = Macrocycle.new
	end

	def create
		@macrocycle = Macrocycle.new(macrocycle_params)
		if @macrocycle.save
			redirect_to plans_path
		else
			render :new
		end
	end

	def edit
		@macrocycle = Macrocycle.find(params[:id])
	end

	def update
		@macrocycle = Macrocycle.find(params[:id])

		if @macrocycle.update_attributes(macrocycle_params)
			redirect_to plans_path
		else
			render :edit
		end
	end

	def destroy
		@macrocycle = Macrocycle.find(params[:id])
		@macrocycle.destroy
		redirect_to plans_path
	end

	private
	def macrocycle_params
		params.require(:macrocycle).permit(:title, :start_date, :end_date, :plan_id)
	end

end

app/controllers/mesocycles_controller.rb
class MesocyclesController < ApplicationController

	def new
		@mesocycle = Mesocycle.new
	end

	def create
		@mesocycle = Mesocycle.new(mesocycle_params)
		if @mesocycle.save
			redirect_to plans_path
		else
			render :new
		end
	end

	def edit
		@mesocycle = Mesocycle.find(params[:id])
	end

	def update
		@mesocycle = Mesocycle.find(params[:id])

		if @mesocycle.update_attributes(mesocycle_params)
			redirect_to plans_path
		else
			render :edit
		end
	end

	def destroy
		@mesocycle = Mesocycle.find(params[:id])
		@mesocycle.destroy
		redirect_to plans_path
	end

	private
	def mesocycle_params
		params.require(:mesocycle).permit(:title, :macrocycle_id)
	end

end

app/controllers/microcycles_controller.rb
class MicrocyclesController < ApplicationController
	def new
		@microcycle = Microcycle.new
	end

	def create
		@microcycle = Microcycle.new(microcycle_params)
		if @microcycle.save
			redirect_to plans_path
		else
			render :new
		end
	end

	def edit
		@microcycle = Microcycle.find(params[:id])
	end

	def update
		@microcycle = Microcycle.find(params[:id])

		if @microcycle.update_attributes(microcycle_params)
			redirect_to plans_path
		else
			render :edit
		end
	end

	def destroy
		@microcycle = Microcycle.find(params[:id])
		@microcycle.destroy
		redirect_to plans_path
	end

	private
	def microcycle_params
		params.require(:microcycle).permit(:title, :mesocycle_id)
	end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

	def home
	end

	def index
		@plans = Plan.where("user_id", "%{current_user.id}%")
		@plan = Plan.new
		@macrocycle = Macrocycle.new
		@mesocycle = Mesocycle.new
		@microcycle = Microcycle.new
		@day = Day.new
		@exercise = Exercise.new
	end

	def new
		@plan = Plan.new
	end

	def create
		@plan = Plan.new(plan_params)
		if @plan.save
			redirect_to plans_path
		else
			render :new
		end
	end

	def edit
	end

	def destroy
		@plan = Plan.find(params[:id])
		@plan.destroy
		redirect_to plans_path
	end

	private
	def plan_params
		params.require(:plan).permit(:user_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/macrocycles_helper.rb
module MacrocyclesHelper
end

app/helpers/mesocycles_helper.rb
module MesocyclesHelper
end

app/helpers/microcycles_helper.rb
module MicrocyclesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/macrocycles/new.html.erb
<h1>Macrocycles#new</h1>

<%= form_for(@macrocycle) do |f| %>

	<%= f.submit %>
<% end %>

app/views/plans/_plan.html.erb
<h1>Exercise plans</h1>
<% @plans.each do |plan| %>

	<ul>Plan ID: <%= plan.id %>
		<%= button_to "Delete plan", plan_path(plan), method: :delete %>
		<ul>Add macrocycle to plan
			<%= form_for(@macrocycle) do |f| %>
			<li>
				Title: <%= f.text_field :title %>
			</li>		
				<%= f.hidden_field :plan_id, {value: plan.id} %>
			<li>
				<%= f.submit %>
			</li>
			<% end %>
		</ul>
	</ul>

	<ul>Plan <%= plan.id %> Macrocycles
		<% plan.macrocycles.each do |macrocycle| %>
			<ul>Macrocycle ID: <%= macrocycle.id %>
				<li>
					Title: <%= macrocycle.title %>
				</li>
				<li>
				<%= button_to "Delete macrocycle", macrocycle_path(macrocycle), method: :delete %>
				</li>
				<li>
					<ul>Add mesocycle to macrocycle <%= macrocycle.id %>
						<%= form_for(@mesocycle) do |f| %>
						<li>
							Title: <%= f.text_field :title %>
						</li>
							<%= f.hidden_field :macrocycle_id, {value: macrocycle.id} %>
						<li>
							<%= f.submit %>
						</li>
						<% end %>
					</ul>
				</li>
				
				<li>
					<ul>Macro <%= macrocycle.id %> Mesocycles
						<% macrocycle.mesocycles.each do |mesocycle| %>

							<ul>Mesocycle ID: <%= mesocycle.id %>
								<li>
									Title: <%= mesocycle.title %>
								</li>
								<li>
									<%= button_to "Delete mesocycle", mesocycle_path(mesocycle.id), method: :delete %>
								</li>
								
								<li>
									<ul>Add microcycle to mesocycle
										<%= form_for(@microcycle) do |f| %>
										<li>
											Title: <%= f.text_field :title %>
										</li>
											<%= f.hidden_field :mesocycle_id, {value: mesocycle.id} %>
										<li>
											<%= f.submit %>
										</li>
										<% end %>
									</ul>
								</li>

								<li>
									<ul>
										<% mesocycle.microcycles.each do |microcycle| %>
											<ul>Microcycle ID: <%= microcycle.id %>
												<li>
													Title: <%= microcycle.title %>
												</li>
												<li>
													<%= button_to "Delete microcycle", microcycle_path(microcycle.id), method: :delete %>
												</li>

												<li>
													<ul>Add day to microcycle
														<%= form_for(@day) do |f| %>
														<li>
															<%= f.text_field :title %>
														</li>
															<%= f.hidden_field :microcycle_id, {value: microcycle.id} %>
														<li>
															<%= f.submit %>
														</li>
														<% end %>
													</ul>
												</li>
												
												<li>
													<ul>Microcycle <% microcycle.id %> days
														<% microcycle.days.each do |day| %>
															<ul>Day ID: <%= day.id %>
																<li>
																	Title: <%= day.title %>
																</li>

																<li>Exercises:
																	<ul>
																		<% day.exercises.each do |exercise| %>
																		<li>
																			Exercise: <%= exercise.name %>
																		</li>
																		<li>
																			<%= button_to "Delete exercise", exercise_path(exercise.id), method: :delete %>
																		</li>
																		<% end %>
																	</ul>
																</li>

																<li>
																	<%= button_to "Delete day", day_path(day.id), method: :delete %>
																</li>

																<li>
																	<ul>Add exercise to day
																		<%= form_for(@exercise) do |f| %>
																		<li>
																			Name: <%= f.text_field :name %>
																		</li>
																		<li>
																			<%= f.hidden_field :day_id, {value: day.id} %>
																		</li>
																		<li>
																			<%= f.submit %>
																		</li>
																		<% end %>
																	</ul>
																</li>

															</ul>
														<% end %>
													</ul>
												</li>		
											</ul>
										<% end %>
									</ul>
								</li>
							</ul>

						<% end %>
					</ul>
				</li>

			</ul>
		<% end %>
	</ul>

<% end %>

app/views/plans/edit.html.erb
<h1>Plans#edit</h1>

app/views/plans/home.html.erb
<h1>Plans#home</h1>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<ul>Options
	<li>
		<%= link_to "View my exercise plans", plans_path(current_user) %>
	</li>
</ul>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path  %>
<% end %>

app/views/plans/index.html.erb
<h1>Plans#index</h1>
<%= link_to "Home", root_path %>

<ul>Options
	<li>Create a new exercise plan:
		<%= form_for(@plan) do |f| %>
			<%= f.hidden_field :user_id, {value: current_user.id} %>
			<%= f.submit %>
		<% end %>	
	</li>
</ul>

<% if @plans.length > 0 %>
	<%= render 'plan' %>
<% else %>
	No plans exist!
<% end %>

<div id="works">
</div>

app/views/plans/new.html.erb
<h1>Plans#new</h1>

<%= form_for(@plan) do |f| %>
	<%= f.hidden_field :user_id, {value: current_user.id} %>
	<%= f.submit %>
<% end %>